export enum AvailableTestFlashcardModel {
    WithoutPhotoAndOptions = 'VOCABULARY.STUDY_LANGUAGE.MODELS.WITHOUT_PHOTO_AND_OPTIONS',
    WithOptions = 'VOCABULARY.STUDY_LANGUAGE.MODELS.WITH_OPTIONS',
    WithPhoto = 'VOCABULARY.STUDY_LANGUAGE.MODELS.WITH_PHOTO',
    WithPhotoAndOptions = 'VOCABULARY.STUDY_LANGUAGE.MODELS.WITH_PHOTO_AND_OPTIONS'
}